# Generated by Django 4.1.7 on 2023-02-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date',
            new_name='date_posted',
        ),
    ]
